### ISSUE TITLE
Generate JAR files for the library

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/opentripplanner-client-library#6]
**Description**
Although we have the `ios` and `android` module set up, we need to expect the library to generate files as well for use on desktop JAVA since the AAR files cannot be understood by then. 

**Solution**
We may need another module set up similar to `ios` or `android` that can be outputted as `jar`. 

**Alternative**
N/A

**Comment by barbeau** [comment]
As part of this process we will likely need to define the group and artifact name like we would for any Maven artifact, so it can be referenced in a `<dependency>` section in the desktop application `pom.xml`. Here's how this was configured in another project, although I don't know if this applies to KMM:
https://github.com/MobilityData/gtfs-validator/blob/44e3503db75f80fd77be4b9f3fae2e1d1b5b5883/main/build.gradle#L25

**Comment by barbeau** [comment]
This project looks like it generates a desktop Java library, and it looks like `jvm` keyword in the build.gradle is what configures it:
https://github.com/joreilly/BikeShare/blob/main/common/build.gradle.kts

Note that it's a bikeshare demo app (😄) but also uses the Compose for Desktop and Jetpack Compose for desktop and Android UIs, respectively.

**Comment by BumbleFlash** [comment]
@barbeau ktor JVM supports 4 engines. 

- Apache
- Java
- Jetty
- CIO

You can read more about it in here https://ktor.io/docs/http-client-engines.html

The BikeShare demo app library uses Apache. Which ones are we using?

**Comment by barbeau** [comment]
Good question - maybe Java (JVM)﻿ so it's native? Have you seen any other advantages or disadvantages?

**Comment by barbeau** [comment]
>I have added the JVM configuration but I'm still confused how to export it as JAR. Don't we need a main class to make a JAR file? 
 
No, you can create a JAR for any class, just like the old OTP POJOs project. You will probably need to define the artifact ID and group ID as mentioned in https://github.com/CUTR-at-USF/opentripplanner-client-library/issues/6#issuecomment-812562208.

>Also, should I create a desktop module with main and test similar to the app module in the project? or should I export it to mavenLocal() and test it on our analyzer? 

Yes, I think adding a demo of the desktop app here would be useful - you could then copy/paste that code into the analyzer project (after depending on mavenLocal() as you say).

**Comment by barbeau** [comment]
After you add the JVM config, does `/.gradlew :library:build` produce a JAR somewhere in `library/build/outputs`, like it outputs the AAR to `library/build/outputs/aar`?

**Comment by BumbleFlash** [comment]
When I run the `gradlew` command, I see 4 files outputted to `library/build/libs`. The `libs` folder contains these files:-

- `library-1.0.jar`
- `library-jvm-1.0.jar`
- `library-metadata-1.0-all.jar`
- `library-metadata-1.0-sources.jar`

Is this what we're looking for?

**Comment by barbeau** [comment]
I think so! `library-jvm-1.0.jar` seems the most promising. I'd try to drop this into the analyzer project (either by copying JAR as local dependency, or by doing the equivalent to `mvn install` on this project) and see if you can get it to recognize the dependency.

**Comment by barbeau** [comment]
@BumbleFlash See these docs:
* https://kotlinlang.org/docs/multiplatform-library.html#publish-your-library-to-the-local-maven-repository

**Comment by BumbleFlash** [comment]
@barbeau I was able to publish the library to the local maven repository and log the data in the project! Here's the link to the test repository: https://github.com/BumbleFlash/opentripplanner-multiplatform-test and the updated library code has been pushed to #13. 

One catch is, when I run the test application using `gradlew build`, the exceptions mentioned below are thrown. 

```
C:\Users\sudarshans\IdeaProjects\opentripplanner-multiplatform-test>gradlew build

BUILD SUCCESSFUL in 3s
3 actionable tasks: 1 executed, 2 up-to-date
C:\Users\sudarshans\IdeaProjects\opentripplanner-multiplatform-test>java -jar build/libs/opentripplanner-multiplatform-test-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at MainKt.main(Main.kt:2)
        at MainKt.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutineScope
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 11 more

```
The CoroutineScope is used by the desktop application and not by the library. 

However, I have added the configuration to generate a `fatJar` file. To build it, type `gradle fatJar` on the command line and run the jar file generated in `build/libs`. It seems to be working fine this way.

**Comment by BumbleFlash** [comment]
Also, there's a small workaround in the test application. Since it's a coroutine, I had to delay the main function for 10 seconds in order to see the results and I didn't pay much attention to it as it's a test app. There should be an `await` function I don't know of.

**Comment by barbeau** [comment]
>when I run the test application using gradlew build, the exceptions mentioned below are thrown.

Yes, this is expected as by default the dependencies for the test app aren't bundled with the JAR unless you build a "fat" or "shaded" JAR as you say. We'll need to worry about that in the desktop application as you say, but it shouldn't have any impact on the library!

**Comment by barbeau** [comment]
>Also, there's a small workaround in the test application. Since it's a coroutine, I had to delay the main function for 10 seconds in order to see the results and I didn't pay much attention to it as it's a test app. There should be an await function I don't know of.

That's fine for the test app, but in the analyzer application we'll need to figure out a more elegant solution. We should be able to wait on the thread running the co-routine as you say, although I'm not sure what the Java-Kotlin interop looks like for that. If it's not simple we may just convert the analyzer application to Kotlin.

**Comment by BumbleFlash** [comment]
@barbeau I'm curious to find out how we can use Coroutines with Java. This blog seems to be informative upon a quick read. https://medium.com/@esocogmbh/coroutines-in-pure-java-65661a379c85. However, from a quick surf, converting the analyzer to Kotlin seems to be neater and more elegant.
