### ISSUE TITLE
Add iOS support

### ISSUE THREAD

**Issue by BumbleFlash** [CUTR-at-USF/opentripplanner-client-library#7]
**Description**
The library was written on the windows machine hence, none of the `ios` code was supported. 

**Solution**
1) Install Android Studio in a macOS
2) Go to the website: https://www.raywenderlich.com/19144111-kotlin-multiplatform-project-for-android-and-ios-getting-started
3) Read and implement the sections, "Integrating into iOS" and "Fetching Data in ioS"

**Alternatives**
N/A

**Comment by barbeau** [comment]
Also see this project, which the KMM docs point to as a sample, looks like a good full-featured example of a KMM SDK project that includes iOS and Android examples, if we need it later:
https://gitlab.com/terrakok/gitlab-client/-/tree/develop/

**Comment by barbeau** [comment]
@aaronbrethorst and @ualch9 Here's the issue for iOS evaluation and further development if needed on this project. See above for some notes ☝️. Please feel free to add more notes in this issue and you learn more about what does and doesn't work on iOS, and PRs for necessary changes or an iOS demo app if you'd like.

**Comment by ualch9** [comment]
> 1. Install AS in a macOS

AS is Android Studio?

**Comment by aaronbrethorst** [comment]
@ualch9 FYI - my hope is that we can consume this library in a 'headless' fashion on iOS and build a native UI for it in Swift. 

@barbeau @BumbleFlash Ideally, we'd be able to pull this code into OBAKit as a Swift Package Manager (SPM) dependency. I found this tutorial describing the process for configuring it thusly, and it doesn't sound too onerous for someone who knows their way around the Android ecosystem. Can you take a peek? https://johnoreilly.dev/posts/kotlinmultiplatform-swift-package/

**Comment by barbeau** [comment]
>AS is Android Studio?

Yes, sorry - updated that, and just beefed up the README some too

**Comment by barbeau** [comment]
>I found this tutorial describing the process for configuring it thusly, and it doesn't sound too onerous for someone who knows their way around the Android ecosystem. Can you take a peek? https://johnoreilly.dev/posts/kotlinmultiplatform-swift-package/

@aaronbrethorst Awesome, thanks for the pointer - yes, we'll take a look.

**Comment by barbeau** [comment]
@aaronbrethorst @ualch9 Do you have a preference for where the package would be published? Looks like the above article talks about using GitHub Packages - would that work for you? I need to reevaluate where all our artifacts (USF) are being published because JCenter is being sunset, and GitHub Packages seems like a good option.

**Comment by aaronbrethorst** [comment]
GitHub Packages sounds...fine? Our SPM dependencies all happen to be on GitHub at present, but I believe SPM just needs a Git repository URL (e.g. `https://github.com/apple/swift-protobuf.git`)

**Comment by ualch9** [comment]
afaik, spm only requires a `Package.swift` (package configuration file) in the git repo's root for it to be a Swift Package. SPM grabs the package from its git URL, as aaron mentioned. there should be no need to rehost the package, for example, like on `npm` or github packages.

**Comment by barbeau** [comment]
WIP PR for creating a Swift Package at https://github.com/CUTR-at-USF/opentripplanner-client-library/pull/12.
